// Code generated by tools/generate-protocol.php from protocol/protocol.json. DO NOT EDIT.

package proto

const (
	Name                = "lnms-webterm"
	Version             = 1
	Subprotocol         = "lnms-webterm.v1"
	MinSupportedVersion = 1
	MaxSupportedVersion = 1

	SecretBytes          = 32
	HKDFSalt             = "lnms-webterm/v1"
	HKDFInfoControl      = "control"
	SignaturePrefix      = "v1="
	TimestampSkewSeconds = 30
	NonceCacheSeconds    = 120

	HeaderTimestamp    = "X-WebTerm-Timestamp"
	HeaderNonce        = "X-WebTerm-Nonce"
	HeaderSignature    = "X-WebTerm-Signature"
	HeaderRejectReason = "X-WebTerm-Reject"

	PathHello             = "/api/v1/hello"
	PathSessionCreate     = "/api/v1/sessions"
	PathHostkeyScan       = "/api/v1/hostkey/scan"
	PathSessionCredential = "/api/v1/sessions/{id}/credential"
	PathSessionList       = "/api/v1/sessions"
	PathSessionDelete     = "/api/v1/sessions/{id}"
	PathSessionNotice     = "/api/v1/sessions/{id}/notice"
	PathHealthz           = "/healthz"
	PathReadyz            = "/readyz"

	TicketBytes      = 32
	TicketTTLSeconds = 30

	MaxOutputBufferBytes  = 262144
	MaxFrameBytes         = 65536
	WSPingIntervalSeconds = 20
	WSPongTimeoutSeconds  = 60
)

// CloseCodes maps WebSocket close codes to their stable string meaning.
var CloseCodes = map[int]string{
	4400: "protocol_error",
	4401: "ticket_invalid_or_expired",
	4403: "authorization_revoked",
	4408: "idle_timeout",
	4409: "session_superseded",
	4413: "output_buffer_overrun",
	4429: "concurrency_limit",
	4500: "gateway_internal_error",
	4503: "upstream_unreachable",
}
