#!/bin/sh
# Emit a single self-contained install.sh for the release page.
#
# install.sh sources webserver.sh and repository.sh from its own directory,
# which is right when it ships in a package or a tarball and wrong for the
# documented "download it, read it, run it" flow: that told an operator to fetch
# three files, and fetching two of them produced a script that silently skipped
# the proxy step and could not reach the package repository.
#
# The modules are concatenated ahead of install.sh's body. Its source-loops stay
# in place and simply find nothing to load, because the functions are already
# defined -- so the bundled and unbundled forms run the same code path.
set -eu

cd "$(dirname "$0")/.."
OUT="${1:-dist/install.sh}"
mkdir -p "$(dirname "$OUT")"

{
    printf '#!/bin/sh\n'
    printf '# librenms-webterm installer -- generated bundle of packaging/{repository,webserver,install}.sh\n'
    printf '# Source of truth is the repository; do not edit this file.\n\n'
    sed '1{/^#!/d;}' packaging/repository.sh
    printf '\n'
    sed '1{/^#!/d;}' packaging/webserver.sh
    printf '\n'
    # Strip the module source-loops. Leaving them in is not merely redundant:
    # install.sh installs the package, which ships its own copy of these modules
    # under /usr/share/librenms-webterm -- so the loop finds the RELEASED copy
    # and redefines the functions the bundle just supplied. A bundle carrying a
    # fix then runs the older code and reports the old symptom, which is a
    # genuinely baffling thing to debug.
    awk '
        /^for _dir in "\$\(dirname "\$0"\)" \/usr\/share\/librenms-webterm/ { skip = 1 }
        skip && /^done$/ { skip = 0; print "# (module source-loop removed: this is the bundled installer)"; next }
        !skip { print }
    ' packaging/install.sh | sed '1{/^#!/d;}'
} > "$OUT"

chmod 0755 "$OUT"
sh -n "$OUT" || { echo "bundle-installer: the generated script does not parse" >&2; exit 1; }

# A bundle that lost a module is worse than no bundle: it runs, skips the proxy,
# and reports success. Assert both are actually in there.
# The source-loops must be gone, or an installed package silently shadows the
# bundle's own copy of these functions.
grep -q 'if \[ -r "\$_dir/webserver.sh" \]' "$OUT" && {
    echo "bundle-installer: a module source-loop survived into $OUT" >&2
    exit 1
}

for fn in webterm_configure_webserver webterm_install_from_repository webterm_verify_proxy; do
    grep -q "^$fn()" "$OUT" || {
        echo "bundle-installer: $fn is missing from $OUT" >&2
        exit 1
    }
done

echo "bundle-installer OK: $OUT ($(wc -l < "$OUT") lines)"
