<?php

declare(strict_types=1);

/**
 * Generates the PHP and Go protocol constant files from protocol/protocol.json.
 *
 *   php tools/generate-protocol.php
 *
 * CI runs this and then asserts `git diff --exit-code`, so the two
 * implementations can never drift from the spec or from each other.
 */
$root = dirname(__DIR__);
$spec = json_decode((string) file_get_contents($root.'/protocol/protocol.json'), true, 512, JSON_THROW_ON_ERROR);

$banner = <<<'TXT'
Code generated by tools/generate-protocol.php from protocol/protocol.json. DO NOT EDIT.
TXT;

/* ----------------------------------------------------------------- PHP --- */

$cp = $spec['control_plane'];
$php = "<?php\n\ndeclare(strict_types=1);\n\n// {$banner}\n\nnamespace AdaptiveDataNetworks\\WebTerm;\n\nfinal class Protocol\n{\n";
$php .= '    public const NAME = '.var_export($spec['name'], true).";\n";
$php .= "    public const VERSION = {$spec['version']};\n";
$php .= '    public const SUBPROTOCOL = '.var_export($spec['subprotocol'], true).";\n";
$php .= "    public const MIN_SUPPORTED_VERSION = {$spec['min_supported_version']};\n";
$php .= "    public const MAX_SUPPORTED_VERSION = {$spec['max_supported_version']};\n\n";
$php .= "    public const SECRET_BYTES = {$cp['secret_bytes']};\n";
$php .= '    public const HKDF_HASH = '.var_export($cp['hkdf_hash'], true).";\n";
$php .= '    public const HKDF_SALT = '.var_export($cp['hkdf_salt'], true).";\n";
$php .= '    public const HKDF_INFO_CONTROL = '.var_export($cp['hkdf_info_control'], true).";\n";
$php .= '    public const SIGNATURE_PREFIX = '.var_export($cp['signature_prefix'], true).";\n";
$php .= "    public const TIMESTAMP_SKEW_SECONDS = {$cp['timestamp_skew_seconds']};\n";
$php .= "    public const NONCE_CACHE_SECONDS = {$cp['nonce_cache_seconds']};\n\n";
foreach ($cp['headers'] as $k => $v) {
    $php .= '    public const HEADER_'.strtoupper($k).' = '.var_export($v, true).";\n";
}
$php .= "\n";
foreach ($cp['endpoints'] as $name => $ep) {
    $php .= '    public const EP_'.strtoupper($name).'_METHOD = '.var_export($ep['method'], true).";\n";
    $php .= '    public const EP_'.strtoupper($name).'_PATH = '.var_export($ep['path'], true).";\n";
}
$t = $spec['ticket'];
$php .= "\n    public const TICKET_BYTES = {$t['bytes']};\n";
$php .= "    public const TICKET_TTL_SECONDS = {$t['ttl_seconds']};\n\n";
foreach ($spec['limits'] as $k => $v) {
    if (! is_int($v)) {
        continue;
    }
    $php .= '    public const '.strtoupper($k)." = {$v};\n";
}
$php .= "\n    /** @var list<string> */\n    public const AUTH_METHODS = ".shortList($spec['auth_methods']).";\n";
$php .= "\n    /** @var list<string> */\n    public const HOST_KEY_POLICIES = ".shortList($spec['host_key_policies']).";\n";
$php .= "\n    /** @var array<int, string> */\n    public const CLOSE_CODES = [\n";
foreach ($spec['close_codes'] as $code => $meaning) {
    $php .= "        {$code} => ".var_export($meaning, true).",\n";
}
$php .= "    ];\n}\n";

file_put_contents($root.'/src/Protocol.php', $php);

/* ------------------------------------------------------------------ Go --- */

$go = "// {$banner}\n\npackage proto\n\nconst (\n";
$go .= "\tName = ".goStr($spec['name'])."\n";
$go .= "\tVersion = {$spec['version']}\n";
$go .= "\tSubprotocol = ".goStr($spec['subprotocol'])."\n";
$go .= "\tMinSupportedVersion = {$spec['min_supported_version']}\n";
$go .= "\tMaxSupportedVersion = {$spec['max_supported_version']}\n\n";
$go .= "\tSecretBytes = {$cp['secret_bytes']}\n";
$go .= "\tHKDFSalt = ".goStr($cp['hkdf_salt'])."\n";
$go .= "\tHKDFInfoControl = ".goStr($cp['hkdf_info_control'])."\n";
$go .= "\tSignaturePrefix = ".goStr($cp['signature_prefix'])."\n";
$go .= "\tTimestampSkewSeconds = {$cp['timestamp_skew_seconds']}\n";
$go .= "\tNonceCacheSeconds = {$cp['nonce_cache_seconds']}\n\n";
foreach ($cp['headers'] as $k => $v) {
    $go .= "\tHeader".goCamel($k).' = '.goStr($v)."\n";
}
$go .= "\n";
foreach ($cp['endpoints'] as $name => $ep) {
    $go .= "\tPath".goCamel($name).' = '.goStr($ep['path'])."\n";
}
$go .= "\n\tTicketBytes = {$t['bytes']}\n";
$go .= "\tTicketTTLSeconds = {$t['ttl_seconds']}\n\n";
foreach ($spec['limits'] as $k => $v) {
    if (! is_int($v)) {
        continue;
    }
    $go .= "\t".goCamel($k)." = {$v}\n";
}
$go .= ")\n\n// CloseCodes maps WebSocket close codes to their stable string meaning.\nvar CloseCodes = map[int]string{\n";
foreach ($spec['close_codes'] as $code => $meaning) {
    $go .= "\t{$code}: ".goStr($meaning).",\n";
}
$go .= "}\n";

$goPath = $root.'/gateway/internal/proto/proto.go';
file_put_contents($goPath, $go);

// gofmt's alignment rules are not worth reimplementing in PHP, and a file that
// fails `gofmt -l` fails CI. Shell out when the toolchain is available.
$gofmt = locateGofmt();
if ($gofmt !== null) {
    exec(escapeshellcmd($gofmt).' -w '.escapeshellarg($goPath), $out, $code);
    if ($code !== 0) {
        fwrite(STDERR, "warning: gofmt failed on {$goPath}\n");
    }
} else {
    fwrite(STDERR, "warning: gofmt not found; generated Go may not be gofmt-clean.\n");
    fwrite(STDERR, "         Install Go or run `gofmt -w gateway/internal/proto/proto.go`.\n");
}

echo "generated src/Protocol.php and gateway/internal/proto/proto.go\n";

/**
 * Find gofmt on PATH, or in the standard install locations. Contributors
 * install Go in several places and a missing gofmt should degrade to a warning,
 * never a wrong file.
 */
function locateGofmt(): ?string
{
    $env = getenv('GOFMT');
    if (is_string($env) && $env !== '' && is_executable($env)) {
        return $env;
    }

    $onPath = trim((string) shell_exec('command -v gofmt 2>/dev/null'));
    if ($onPath !== '' && is_executable($onPath)) {
        return $onPath;
    }

    $home = getenv('HOME') ?: '';
    foreach ([
        $home.'/.local/go/bin/gofmt',
        '/usr/local/go/bin/gofmt',
        '/usr/lib/go/bin/gofmt',
        $home.'/go/bin/gofmt',
    ] as $candidate) {
        if (is_executable($candidate)) {
            return $candidate;
        }
    }

    return null;
}

function shortList(array $v): string
{
    return '['.implode(', ', array_map(fn ($x) => var_export($x, true), $v)).']';
}

function goStr(string $s): string
{
    return '"'.addcslashes($s, "\"\\\n\t").'"';
}

function goCamel(string $s): string
{
    $s = str_replace(['_', '-'], ' ', $s);
    $s = ucwords($s);
    $s = str_replace(' ', '', $s);

    return strtr($s, ['Ws' => 'WS', 'Ttl' => 'TTL', 'Url' => 'URL', 'Id' => 'ID']);
}
