<?php

declare(strict_types=1);

// Code generated by tools/generate-protocol.php from protocol/protocol.json. DO NOT EDIT.

namespace Adn\WebTerm;

final class Protocol
{
    public const NAME = 'lnms-webterm';
    public const VERSION = 1;
    public const SUBPROTOCOL = 'lnms-webterm.v1';
    public const MIN_SUPPORTED_VERSION = 1;
    public const MAX_SUPPORTED_VERSION = 1;

    public const SECRET_BYTES = 32;
    public const HKDF_HASH = 'sha256';
    public const HKDF_SALT = 'lnms-webterm/v1';
    public const HKDF_INFO_CONTROL = 'control';
    public const SIGNATURE_PREFIX = 'v1=';
    public const TIMESTAMP_SKEW_SECONDS = 30;
    public const NONCE_CACHE_SECONDS = 120;

    public const HEADER_TIMESTAMP = 'X-WebTerm-Timestamp';
    public const HEADER_NONCE = 'X-WebTerm-Nonce';
    public const HEADER_SIGNATURE = 'X-WebTerm-Signature';
    public const HEADER_REJECT_REASON = 'X-WebTerm-Reject';

    public const EP_HELLO_METHOD = 'GET';
    public const EP_HELLO_PATH = '/api/v1/hello';
    public const EP_SESSION_CREATE_METHOD = 'POST';
    public const EP_SESSION_CREATE_PATH = '/api/v1/sessions';
    public const EP_SESSION_CREDENTIAL_METHOD = 'POST';
    public const EP_SESSION_CREDENTIAL_PATH = '/api/v1/sessions/{id}/credential';
    public const EP_SESSION_LIST_METHOD = 'GET';
    public const EP_SESSION_LIST_PATH = '/api/v1/sessions';
    public const EP_SESSION_DELETE_METHOD = 'DELETE';
    public const EP_SESSION_DELETE_PATH = '/api/v1/sessions/{id}';
    public const EP_SESSION_NOTICE_METHOD = 'POST';
    public const EP_SESSION_NOTICE_PATH = '/api/v1/sessions/{id}/notice';
    public const EP_HEALTHZ_METHOD = 'GET';
    public const EP_HEALTHZ_PATH = '/healthz';
    public const EP_READYZ_METHOD = 'GET';
    public const EP_READYZ_PATH = '/readyz';

    public const TICKET_BYTES = 32;
    public const TICKET_TTL_SECONDS = 30;

    public const MAX_OUTPUT_BUFFER_BYTES = 262144;
    public const MAX_FRAME_BYTES = 65536;
    public const WS_PING_INTERVAL_SECONDS = 20;
    public const WS_PONG_TIMEOUT_SECONDS = 60;

    /** @var list<string> */
    public const AUTH_METHODS = ['signed_certificate', 'password', 'private_key'];

    /** @var list<string> */
    public const HOST_KEY_POLICIES = ['pin', 'tofu_first_connect'];

    /** @var array<int, string> */
    public const CLOSE_CODES = [
        4400 => 'protocol_error',
        4401 => 'ticket_invalid_or_expired',
        4403 => 'authorization_revoked',
        4408 => 'idle_timeout',
        4409 => 'session_superseded',
        4413 => 'output_buffer_overrun',
        4429 => 'concurrency_limit',
        4500 => 'gateway_internal_error',
        4503 => 'upstream_unreachable',
    ];
}
